# cookiecutter-ansible-role: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up
version: '3'
services:

  app:
    restart: always
    image: python:3.6.1
    ports:
      - "80:8000"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/usr/src/
    env_file:
      - .env
